# Generated by Django 5.1 on 2024-08-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_hired',
        ),
    ]
