# Generated by Django 5.1 on 2024-09-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(default='default_user_name', max_length=25),
        ),
    ]
