# Generated by Django 5.1 on 2024-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='advances',
            field=models.IntegerField(default=0),
        ),
    ]
