# Generated by Django 5.1 on 2024-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_name',
            field=models.CharField(max_length=255, null=False, default='default_user_name'),
        ),
    ]