# Generated by Django 5.1 on 2024-09-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_employee_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_name',
            field=models.CharField(default='default_user_name', max_length=50),
        ),
    ]
